services:
  database:
      build:
        context: .
        dockerfile: Dockerfile
      image: postgres-docker:16.4
      container_name: postgres-16.4
      environment:
        - POSTGRES_DB=develop
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      ports:
        - 5432:5432
      volumes:
        - postgres-volume:/var/lib/postgresql/data

  pgadmin4:
    image: dpage/pgadmin4:8.12.0
    container_name: postgres-pgadmin4
    volumes:
      - postgres-pgadmin:/var/lib/pgadmin
    ports:
      - 8888:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@example.com
      - PGADMIN_DEFAULT_PASSWORD=passwd
    depends_on:
      - database

volumes:
  postgres-volume:
  postgres-pgadmin: