services:
  database:
      build:
        context: .
        dockerfile: Dockerfile
      image: my-postgres:16.3
      container_name: my-postgres-16.3
      environment:
        - POSTGRES_DB=test-db
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      ports:
        - 5432:5432
      volumes:
        - ./data:/var/lib/postgresql/data
        - ./init:/docker-entrypoint-initdb.d